left to right direction
skinparam style strictuml
skinparam packageStyle rect
actor Humain
rectangle "Application" {
 (Choisir un profil) as login
 (Ajouter des données) as ad
 (Supprimer des données) as sd
 (Consulter les graphiques) as cg
 (Consulter données) as cd
 (Glycémie) as gly
 (Corpulence) as cor
 (Sommeil) as som
 (Sport) as spo 
}
Humain --> cd
Humain --> ad
Humain --> sd
Humain --> cg
Humain --> login
ad -- ​cor
ad -- som
ad -- gly
ad -- spo
sd -- cor
sd -- som
sd -- gly
sd -- sp
